"""
Adversarial Critic Node — Challenges trade setups generated by the Primary Builders.

Powered by a faster LLM (e.g., llama3.1:8b) to find counter-arguments against the trades,
acting as a ruthless risk manager. Does NOT reject trades; just provides the debate evidence.
"""

import os
import json
import logging
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [NODE:ADVERSARIAL_CRITIC] - %(message)s')

OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "http://localhost:11434/v1")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "ollama")
CRITIC_MODEL = os.getenv("CRITIC_MODEL", "llama3.1:8b") # Use faster model for rapid analysis


def adversarial_critic_node(state: dict) -> dict:
    """
    Debate existing built setups.
    Reads:
      - intraday_setups
      - options_setups
      - market_regime
      - defense_mode
    Writes:
      - critic_debate: list of debate dicts
      - all_evidence
    """
    intraday_setups = state.get("intraday_setups", [])
    options_setups = state.get("options_setups", [])
    market_regime = state.get("market_regime", "NEUTRAL")
    defense_mode = state.get("defense_mode", False)
    
    all_setups = intraday_setups + options_setups
    debate_list = []
    evidence = []

    if not all_setups:
        logging.info("No built setups to critique.")
        return {"critic_debate": []}

    logging.info(f"🕵️  Adversarial Critic finding flaws in {len(all_setups)} built setups using {CRITIC_MODEL}...")

    try:
        from openai import OpenAI
        client = OpenAI(base_url=OPENAI_API_BASE, api_key=OPENAI_API_KEY)
    except Exception as e:
        logging.error(f"Failed to initialize OpenAI client for Critic: {e}")
        return {"critic_debate": []}

    for setup in all_setups:
        symbol = setup.get("symbol")
        direction = setup.get("direction", "UNKNOWN")
        confidence = setup.get("confidence")
        sr = setup.get("support_resistance", {})
        evidence_chain = setup.get("evidence", [])
        entry = setup.get("entry")
        target = setup.get("target")
        sl = setup.get("stoploss")
        
        prompt = f"""You are the Risk Manager / Adversarial Critic for a prop trading desk.
Your job is to find reasons to REJECT a setup proposed by the primary builder agent.

Market Regime: {market_regime}
Defense Mode Active: {defense_mode}
Stock: {symbol}
Proposed Setup: {direction} @ Entry: {entry}, Target: {target}, SL: {sl} (Confidence {confidence}%)
Primary Agent Evidence: {json.dumps(evidence_chain[:3])}
Support/Resistance: {json.dumps(sr)}

Evaluate this setup and construct a ruthless counter-argument based on the technicals and regime.
You must reply strictly in valid JSON format:
{{
  "verdict": "APPROVE" | "VETO",
  "counter_argument": "A punchy 1-2 sentence argument explaining the flaw in the Primary Agent's logic or pointing out high risk."
}}
"""

        try:
            response = client.chat.completions.create(
                model=CRITIC_MODEL,
                messages=[
                    {"role": "system", "content": "You are a ruthless risk manager who strictly returns JSON and finds flaws in trade plans."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1,
                response_format={"type": "json_object"}
            )
            
            raw_response = response.choices[0].message.content
            critique = json.loads(raw_response)
            
            verdict = critique.get("verdict", "VETO")
            argument = critique.get("counter_argument", "Setup carries unquantifiable risk under current conditions.")
            
            logging.info(f"    ↳ {symbol} Critic Verdict: {verdict}. Argument: {argument}")
            
            debate_list.append({
                "symbol": symbol,
                "critic_verdict": verdict,
                "critic_argument": argument
            })
            
            evidence.append({
                "node": "adversarial_critic",
                "symbol": symbol,
                "verdict": verdict,
                "argument": argument
            })

        except Exception as e:
            logging.warning(f"    ↳ {symbol} Critic failed or invalid JSON: {e}. Defaulting to APPROVE.")

    logging.info(f"  Critic complete: Generated arguments for {len(debate_list)} setups.")

    return {
        "critic_debate": debate_list,
        "all_evidence": evidence,
    }
